[IV-24-25] Objetivo 3
MatteoImbrosciano/Medication-Management pull request #15
Opened 2024-11-08 16:47 UTC by MatteoImbrosciano

- [ ] ¿Incluye el fichero iv.yaml las claves de todos los objetivos anteriores?
 - [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un issue?
 - [ ]  ¿Ese issue está asignado a un milestone?
 - [ ]  ¿El milestone incluye, entre sus productos mínimamente viables, laexistencia de herramientas que permitan automatizar tareas?
 - [ ]  ¿Hemos justificado correctamente en caso de elegir un gestor de dependencias el que se use como gestor de tareas?
 - [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
 - [ ] ¿La tarea check efectivamente comprueba la sintaxis de los fuentes existentes y sólo eso?
 - [ ] ¿Se ha comprobado que las instrucciones incluidas en el README.md son completas y correctas?

2024-11-16 11:48 UTC, MatteoImbrosciano commented
@JJ puedes revisarlo

2024-11-18 07:28 UTC, JJ requested changes
Devi eseguire buone prattiche per fare scelte. I criteri vanno sempre di fronte, poi le scelte.

2024-11-18 07:28 UTC, JJ commented on iv.yaml
> +  tareas:
Non c'è niente di ciò alla guida.

2024-11-18 07:28 UTC, JJ commented on docs/gestor_tareas.md
> +Para automatizar las tareas en este proyecto de Python, como la ejecución de pruebas o la verificación del estilo de código, hemos optado por **Poetry**. A continuación se explican las razones que ha
Prima, criteri di acettazzione; poi, la scelta. Leggi [gli errori comuni](https://github.com/JJ/IV-/blob/master/errores/objetivo-3.md)

2024-11-18 07:28 UTC, JJ commented on pyproject.toml
> +command = "flake8"
`flake8` fa molto di più che controlare la sintassi.

2024-11-18 09:15 UTC, MatteoImbrosciano commented
@JJ ho modificato le cose richieste da lei. Spero che tutto vada bene.

2024-11-20 16:49 UTC, MatteoImbrosciano commented
@JJ puedes revisar

2024-11-20 17:21 UTC, JJ requested changes
Per piacere, leggi la guida del oggetivo 3. Non è un anunzio d'una scelta. È un processo per fare la scelta.

2024-11-20 17:21 UTC, JJ commented on docs/gestor_dependencias.md
> +En el proyecto de gestión de medicamentos en Python, hemos elegido **Poetry** como gestor de dependencias, una herramienta moderna y ampliamente utilizada en la comunidad de Python. A continuación se
1. Dire quali sono i criteri
2. Presentare tutti quelli che eseguono quelli criteri e fino a che punto.
3. Fare la scelta

Come ho detto adesso, non si può fare la scelta da solo.

2024-11-20 19:29 UTC, MatteoImbrosciano commented on docs/gestor_dependencias.md
> +En el proyecto de gestión de medicamentos en Python, hemos elegido **Poetry** como gestor de dependencias, una herramienta moderna y ampliamente utilizada en la comunidad de Python. A continuación se
Grazie per il feedback. Ho rivisto il documento aggiungendo i criteri di selezione e un'analisi comparativa di PDM, Hatch e Poetry. Ho giustificato la scelta di Poetry basandomi sui criteri definiti, come richiesto. Le modifiche sono ora integrate nel file.

2024-11-20 19:29 UTC, MatteoImbrosciano commented
@JJ

2024-11-21 06:29 UTC, JJ reviewed
Come dice il file di errori comuni, quando si trova un "patrone impiegato tante volte", sia di un'AI, sia d'un tutoriale, sia d'un compagno, si dice così e si deve cominciare da capo.

2024-11-21 06:29 UTC, JJ commented on docs/gestor_dependencias.md
> +4. **Creación de entornos virtuales:** Debe facilitar la creación y administración de entornos virtuales específicos para cada proyecto.
È la terza o magari 4ª volta che leggo ciò. Se stai empiegando un'AI, l'AI è sbagliata.
Leggi un'altra volta gli errori comuni.

2024-11-21 10:34 UTC, MatteoImbrosciano commented
@jj

2024-11-21 11:10 UTC, JJ reviewed
Se stai rescrivendo tutto da solo, sei sbagliato, perchè non ho richiesto ciò. Se lo fai colle AI, stai doppiamente sbagliato.

2024-11-21 11:10 UTC, JJ commented on docs/gestor_dependencias.md
> +2. **Manejo de versiones:** El gestor debe proporcionar un archivo de bloqueo que permita garantizar la coherencia de las dependencias entre entornos.
Ti prego, Matteo, non fai così.

2024-11-21 11:35 UTC, MatteoImbrosciano commented
@JJ l'ho modificato nuovamente cercando di avvicinarmi a quanto richiesto. Lei mi aveva detto di fare un confronto ed arrivare ad una scelta e questo l'ho fatto

2024-11-21 18:48 UTC, JJ requested changes
E non hay detto niente di un command/task runner.

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +En el desarrollo del sistema de gestión de medicamentos en Python, la elección de una herramienta adecuada para la gestión de dependencias es crucial. Este sistema requiere un entorno estable, reprod
Prima di dire quali sono (che non sono soltanto quelli lì, invece ci sono di più) devi dire come l'hai cercato e chè stai cercando. E perchè sono questi l'unici che hai considerato.

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +El análisis se basó en criterios claros previamente definidos, adaptados a las necesidades específicas del proyecto. Este enfoque asegura una decisión informada y justificada, evitando soluciones arb
Macchè, Matteo...

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +2. **Gestión de versiones consistente:**
Leggi quello que dici sul criteri che *tutti* eseguono. Se non fanno una gestione "consistente*, a chè servono?

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +3. **Facilidad de uso:**
Hai visto il file di errori comuni? Cosa dice di criteri non oggetivi?

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +4. **Soporte para entornos virtuales:**
L'AI sempre dice questo. Un'altra volta, è inutile dirlo qui. Se non fa supporto ambienti virtuali, a chè serve?

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +5. **Popularidad y soporte de la comunidad:**
Se parliamo di questo, devi segnare ciò con uno numero. Hai cercato qualcosa che fa misura della popularità?

2024-11-21 18:48 UTC, JJ commented on docs/gestor_dependencias.md
> +**PDM** es una herramienta moderna que utiliza el formato `pyproject.toml` y sigue el estándar PEP 582, lo que la alinea con las prácticas actuales de Python. Su enfoque principal es simplificar la g
Sempre meno letteratura, per piacere. Dimi soltanto come si realizza i criteri sopra. E basta.

2024-11-21 19:24 UTC, MatteoImbrosciano commented
Se non va bene questo vuol dire che non ho chiara qualcosa, io uso AI per la traduzione e portare il testo da italiano a spagnolo. Dai un'occhiata se c'è qualcosa di sbagliato domani ne parliamo a lezione. @JJ

2024-11-21 19:53 UTC, JJ commented
Devi usare *sempre* gli issue, anche quando respondi ad uno commento.

2024-11-21 19:54 UTC, JJ commented
Se non hai aperto un'issue per il task manager, devi fare ciò

2024-11-21 19:57 UTC, MatteoImbrosciano commented
si è l'ho aperto l'issue

2024-11-21 19:59 UTC, JJ commented
Quindi devi collegare i commit con quello.
Ma Matteo non si dice `closed` e basta. Devi dire perchè lo stai chiudendo...

2024-11-21 20:04 UTC, MatteoImbrosciano commented
ok ho modificato il commit ed ho scritto ciò che ho fatto

2024-11-22 12:31 UTC, JJ requested changes
La prima cosa che devi fare è dire quali sono i criteri, per il gestore di dependence ed il gestore di tasche

2024-11-22 12:31 UTC, JJ commented on docs/gestor_dependencias.md
> +Abbiamo scelto **Poetry** come gestore di dipendenze per il nostro progetto basandoci sui seguenti criteri:
1. Criteri
2. Instrumenti
3. Scelta

Questo qui è la documentazione di un processo di scelta, no un annunzio di una scelta.

2024-11-22 12:41 UTC, MatteoImbrosciano commented on docs/gestor_dependencias.md
> +Abbiamo scelto **Poetry** come gestore di dipendenze per il nostro progetto basandoci sui seguenti criteri:
ho aggiunto i criteri per la scelta e impostato bene la documentazione con lo schema corretto @JJ

2024-11-22 13:08 UTC, MatteoImbrosciano commented
@JJ  puedes revisar

2024-11-22 16:26 UTC, JJ requested changes
Tutti i criteri devono essere oggetivi e non triviali, anche.

2024-11-22 16:26 UTC, JJ commented on pyproject.toml
> +[tasks.test]
Fino adesso non c'è nessun test e non hai scelto gli instrumenti di test.

2024-11-22 16:26 UTC, JJ commented on pyproject.toml
> +command = "black"
black è lo stesso che flake8. Fa monto di più che controllare la sintassi. Soltanto devi dire se il codice compila oppure no.

2024-11-22 16:26 UTC, JJ commented on docs/gestor_tareas.md
> +| **Poethepoet**        | - Ottimo per automazione complessa<br>- Integrazione nativa con YAML                        | - Complesso da configurare per progetti semplici
Non è lo stesso Poe che Poethepoet?

2024-11-22 16:26 UTC, JJ commented on docs/gestor_tareas.md
> +| **UV**                | - Minimalista e flessibile<br>- Ottimo per piccoli progetti                                | - Richiede configurazioni manuali per task e dipendenze
Credo che soltanto fa il controllo di dependence. Magari sbaglio, pero penso di no.

2024-11-22 16:26 UTC, JJ commented on docs/gestor_tareas.md
> +| **Poetry Tasks**      | - Integrato con il gestore di dipendenze<br>- Semplice da configurare                       | - Meno flessibile rispetto a strumenti dedicati
Questo soltanto travaglia con commandi Python integrati sull'ambiente come `pytest`  o `black`. Non è adatto a eseguire un comando da riga di ordini tipo "rm -rf"

2024-11-22 16:26 UTC, JJ commented on docs/gestor_tareas.md
> +3. **Leggibilità e Manutenibilità:**
leggibilità di cosa?

2024-11-22 16:47 UTC, MatteoImbrosciano commented on docs/gestor_tareas.md
> +| **Poetry Tasks**      | - Integrato con il gestore di dipendenze<br>- Semplice da configurare                       | - Meno flessibile rispetto a strumenti dedicati
Mi consigli di utilizzare allora un makefile?

2024-11-22 16:47 UTC, MatteoImbrosciano commented on docs/gestor_tareas.md
> +| **Poethepoet**        | - Ottimo per automazione complessa<br>- Integrazione nativa con YAML                        | - Complesso da configurare per progetti semplici
si

2024-11-22 19:03 UTC, JJ commented on docs/gestor_tareas.md
> +| **Poetry Tasks**      | - Integrato con il gestore di dipendenze<br>- Semplice da configurare                       | - Meno flessibile rispetto a strumenti dedicati
La scelta é sempre da te. Se non scegli uno strumento che va bene con `pyproject.toml`, devrai aggiungere un'altro file che bisognarà manutenzione e così via. Purtroppo, devi provare que sei bravo cercan istrumenti per un fine determinato, per la precisione, task runners que vanno bene con quello. Sono sicuro che ci sono altri (ma non lavoro molto con Python e veramente non ne so)

2024-11-26 16:19 UTC, MatteoImbrosciano commented
Revisione del mio lavoro @JJ . Ho fatto vari cambiamenti, ritenendo più consono utilizzare il makefile e utilizzare un check della sintassi con l'aggiunto un file .py. Spero che adesso tutto vada bene. Ho testato la sintassi con vari test e tutto mi funzionava correttamente.

2024-11-27 06:29 UTC, JJ requested changes
Dai una occhiata anche agli errori comuni.

2024-11-27 06:29 UTC, JJ commented on Makefile
> +test:
A chè serve fare i test adesso?

2024-11-27 06:29 UTC, JJ commented on check_syntax.py
È possibile che si possa fare lo stesso con una singola riga?

2024-11-27 06:29 UTC, JJ commented on docs/gestor_dependencias.md
> +### 1. **`pip`**
È compatibile con 1? Se non, perchè e qui?

2024-11-27 06:29 UTC, JJ commented on docs/gestor_dependencias.md
> +### 5. **`Poethepoet`**
Sei sicuro questo qui è un gestore di dipendenze?

2024-11-27 09:55 UTC, MatteoImbrosciano commented
pronto per essere revisionato, @JJ

2024-11-28 10:49 UTC, JJ commented
Ricorda che devi chiedere revisione tramite uno commento qui.

2024-11-28 12:05 UTC, MatteoImbrosciano commented
@JJ  revisione

2024-11-28 18:53 UTC, JJ requested changes
Non manca tantissimo. Daje!

2024-11-28 18:53 UTC, JJ commented on check_syntax.py
> +import os, py_compile; [print(f"✔ Sintassi OK: {os.path.join(root, file)}") if py_compile.compile(os.path.join(root, file), doraise=True) else None for root, _, files in os.walk(".") for file in file
È molto semplice controllare la sintassi. Per piacere, cerca la soluzione più semplice.

2024-11-28 18:53 UTC, JJ commented on README.md
> +  - poetry run test
Quella riga è ancora qui.

2024-11-28 18:53 UTC, JJ commented on README.md
> +  - poetry run check_syntax
Cosa fa questo di diverso con `poetry check`?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +4. **Funzionalità avanzate:** Deve offrire funzionalità extra come la gestione degli ambienti virtuali o il blocco delle versioni.
Pensi que questo qui è *oggetivo* come dice [qui](https://jj.github.io/IV/documentos/proyecto/3.Automatizar)?

> Criterios objetivos adicionales: sobre todo, seguridad, prestaciones o algo que se pueda reducir a la cantidad de tiempo que se va a invertir en mantener lo relacionado con la decisión. 

Di cosa parliamo qui?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +2. **Facilità di utilizzo:** Deve semplificare l’installazione e la gestione delle dipendenze.
Al di là di essere adatti a `pyproject.toml`, chè altre facilità serve qui?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +  - **Meno popolare di Poetry** e ha una manutenzione ridotta, con supporto parziale per `pyproject.toml`.
Popolarità non è proprio sopra. Soltanto "facilità", "simplicità", "manutenzione attiva" e "compatibilità". E poi per essere oggetiva devi fare una scelta di come misurare la popolarità.

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +  - Utilizza **`Pipfile`** e **`Pipfile.lock`** per gestire le dipendenze in modo simile a `poetry.lock` di Poetry.
Che c'entra questo qui con i criteri enunziati?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +  - Integra `virtualenv` per creare ambienti virtuali facilmente.
Cosa c'entra con i criteri?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +- **Descrizione:** Gestore di dipendenze che combina l'installazione delle dipendenze e la gestione degli ambienti virtuali.
Adirittura, è un gestore di dipendenze. Se non, perchè sarebbe qui?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +- **Descrizione:** Gestore moderno che usa `pyproject.toml`.
Invece di "descrizione", perchè non fai un collegamento con il repository o con un'altro sito representativo?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +  - Funzionalità avanzate come il blocco delle versioni.
Stai sicuro questo è avanzato? Oppure semplicemente quello che tutti gli instrumenti fanno?

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +- **Contro:** Richiede installazione iniziale.
E quale non? E poi, *non è un criterio*

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +- **Descrizione:** Uno strumento moderno, simile a Poetry, con maggiore flessibilità.
Potrebbe eseguire qui, ma penso che hay già un'idea.

2024-11-28 18:53 UTC, JJ commented on docs/gestor_dependencias.md
> +   curl -sSL https://install.python-poetry.org | python3 -
Perchè `python3`? C'è un'altro python? Devi chiudere anche il "fencing" `````
E questo file non è il luogo per dire questo, soltanto per fare la precisione della scelta.

2024-11-28 18:53 UTC, JJ commented on docs/gestor_tareas.md
> +1. **Flessibilità:** Deve consentire la definizione di tareas personalizzate.
È lo stesso che sopra.

2024-11-28 18:53 UTC, JJ commented on docs/gestor_tareas.md
> +### 2. **`Invoke` (UV)**
Cosa c'entra `uv` con `invoke`?

2024-11-28 18:53 UTC, JJ commented on iv.yaml
> +  orden: "poetry run poe check"
Sei sicuro di questo? Hai letto dove dice "can be used without poetry"?

2024-11-28 18:53 UTC, JJ commented on pyproject.toml
> +black = "^23.7.0"
Questo è ancora qui.

2024-11-28 19:35 UTC, MatteoImbrosciano commented
puedes revisar @JJ

2024-11-29 11:44 UTC, JJ approved these changes
👍

2024-11-29 11:48 UTC, merged