[IV-24-25] Objetivo 1
MatteoImbrosciano/Medication-Management pull request #3
Opened 2024-10-04 11:19 UTC by MatteoImbrosciano

## Sobre los milestones

- [x] ¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?
- [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?
- [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?
- [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
- [x] ¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?
- [x] ¿Todos los milestones describen correctamente un producto y qué lo hace válido, y no un concepto vago, una funcionalidad o una tarea?
- [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
- [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?
- [x] ¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?
- [x] ¿El milestone 0 es mínimo y viable?
- [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?
- [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?

## Sobre las historias de usuario

- [x] ¿He tenido en cuenta en las historias de usuario que se trata de un proyecto que se desplegará en la nube?
- [x] ¿Están descritos todos los conceptos mencionados en las HUs con suficiente claridad, generalmente en documentos aparte?
- [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso de que no lo tengan, se ha escrito un *user journey* para aclararlo?
- [x] ¿Todas las historias de usuario representan un beneficio para el mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios desean hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-10-07 17:33 UTC, Mario25402 commented
Hola mateo te voy a comentar unos detalles sobre tu proyecto:
Primero, creo que la HU1 y la HU2 son muy parecidas o al menos detallan la misma finalidad, quizás sería mejor que la HU1 estuviera enfocada al simple almacenamiento de un ticket online.
Los user journeys son aclaraciones para describir cómo un usuario de tu aplicación usaría la misma, es decir, una explicación por si no queda claro, el recorrido de un usuario concreto. Tú estás describiendo problemas de personas especificas pero eso es lo que debería describirse en las historias de usuario, cosa que ya haces correctamente.
Espero que te sirvan de ayuda mis comentarios!

2024-10-07 20:46 UTC, hossam1522 commented
Buenas, se me ha asignado revisar tu PR. Te dejo algunos comentarios como mejora para que puedas superar exitosamente el objetivo. Junto a mis comentarios y el comentario de Mario, mencionar que no creo que sea necesario indicar el beneficio esperado en los user stories.

2024-10-07 20:47 UTC, hossam1522 reviewed
Buenas, se me ha asignado revisar tu PR. Te dejo algunos comentarios como mejora para que puedas superar exitosamente el objetivo. Junto a mis comentarios y el comentario de Mario, mencionar que no creo que sea necesario indicar el beneficio esperado en los user stories.

2024-10-07 20:47 UTC, hossam1522 commented on docs/milestones.md
> +- **Objetivo:** Analizar las historias de usuario y definir los requisitos clave del dominio del problema a abordar en el desarrollo del MVP. Organizar los conceptos clave de acuerdo con las necesida
En desarrollo ágil no se trabaja con requisitos, ya que los requisitos son siempre satisfacer al cliente. Te recomiendo que le des un par de vueltas y le cambies un poco el enfoque a esta descripción del milestone.

2024-10-07 20:47 UTC, hossam1522 commented on docs/milestones.md
> +- **Historias de Usuario asociadas:** [HU3].
En estos 2 milestones hablas de actualizar o consultar el inventario, pero en ningún milestone indicas que el inventario tiene que implementarse. ¿No sería conveniente introducir otro milestone antes considerando la implementación del inventario, con su stock y datos relevantes?

2024-10-07 20:47 UTC, hossam1522 commented on docs/milestones.md
> +- **Historias de Usuario asociadas:** [HU4].
Teniendo en cuenta mi comentario anterior, considero que la cantidad de milestones quizás es demasiado grande. Puede ser adecuado establecer menos milestones, o considerar algunos como opcionales, tales como este.

2024-10-08 14:14 UTC, MatteoImbrosciano commented
Hola @Mario25402, gracias por el consejo. Edité las historias de usuario.

2024-10-08 14:45 UTC, MatteoImbrosciano commented on docs/milestones.md
> +- **Objetivo:** Analizar las historias de usuario y definir los requisitos clave del dominio del problema a abordar en el desarrollo del MVP. Organizar los conceptos clave de acuerdo con las necesida
Hola, gracias por tu retroalimentación! He revisado la descripción del hito para eliminar la referencia a los "requisitos" y cambiar el enfoque hacia las necesidades de los usuarios y la evolución del dominio del problema. Ahora el hito se centra en el análisis de las historias de usuario y la identificación de los conceptos clave del dominio, utilizando Domain-Driven Design (DDD) como metodología, con el objetivo de mantener flexibilidad y adaptabilidad a las necesidades del cliente durante el desarrollo del MVP.

2024-10-08 14:46 UTC, MatteoImbrosciano commented on docs/milestones.md
> +- **Historias de Usuario asociadas:** [HU3].
He añadido un milestone específico para la creación e implementación del inventario (Milestone 1) antes de los pasos de actualización y de notificaciones. Este nuevo hito garantiza que el inventario básico con el stock y los datos relevantes esté operativo y bien estructurado antes de proceder con el sistema de notificaciones.

2024-10-08 14:50 UTC, MatteoImbrosciano commented on docs/milestones.md
> +- **Historias de Usuario asociadas:** [HU4].
Entiendo que la cantidad de milestones podría ser elevada. He decidido mantener este hito como opcional

2024-10-09 18:58 UTC, jacarmona364 commented
Buenas Matteo, se me ha asignado revisar tu PR, aquí te dejo algunas recomendaciones.

2024-10-09 19:04 UTC, jacarmona364 commented on docs/milestones.md
> +## [M1] Milestone 1: Creación y gestión  del inventario
Dentro de este primer hito lo único que valoraría de nuevo es si realmente este proyecto va a utilizar lógica de negocio o simplemente es una aplicación para almacenar y buscar datos. Entiendo que posteriormente buscarás dar esa vuelta de tuerca analizando los tickets digitales y enviando notificaciones inteligentes al usuario, pero le daría una revisión debido a la potencial complejidad de lo que te marco a continuación.

2024-10-09 19:09 UTC, jacarmona364 commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU2].
En este punto cabría puntualizar si realmente esos tickets electrónicos tendrían un formato específico, si suponemos que todas las farmacias siguen esta modalidad o permanecen ancladas al sistema de recibos tradicional a papel, en cuyo caso sería necesaria una herramienta externa como un lector de facturas o algo similar. Personalmente establecería un formato para ese tipo de tickets electrónicos y eliminaría cualquier ápice de dudas, pero no dejo de pensar que quizás seguiría sin existir un procesado de datos como tal.

2024-10-09 19:15 UTC, jacarmona364 commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU3].
En cuanto al sistema de notificaciones convendría desarrollar un poco más el mecanismo con el que se notificaría al usuario. Te aconsejaría estudiar de nuevo la complejidad de este hito, pues el adicional donde se valora implementar una interfaz de usuario lo veo mucho más importante de cara al usuario y factible. No obstante es el único en el que se podría llegar a ver un procesamiento de datos, quizá convendría buscar otra historia de usuario que nos de pie a algo más que hacer el inventario de medicinas de un usuario, sin llegar a una complejidad demasiado elevada.

2024-10-09 19:24 UTC, jacarmona364 commented
En general me parece un gran proyecto, Matteo, como conclusión te recalcaría algunos puntos mencionados por los otros revisores: intenta que las historias de usuario no tengan la misma finalidad, sino que te permitan desarrollar los hitos independientemente ofreciendo un producto mínimo; estudia la complejidad de introducir un sistema de notificaciones inteligente y repasa en qué caso sería importante procesar datos. De momento es todo por mi parte, ¡mucho ánimo!

2024-10-10 07:32 UTC, MatteoImbrosciano commented on docs/milestones.md
> +## [M1] Milestone 1: Creación y gestión  del inventario
He incluido funciones que le permiten lograr una estabilización mínima y máxima del medicamento, monitoreando automáticamente la liberación del medicamento y el sistema que rastrea la fecha de liberación del medicamento. Ahora creo que estas capacidades van más allá de la simple gestión de datos.

2024-10-10 07:32 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU2].
Tienes razón, es importante aclarar el formato de los billetes electrónicos y cómo se manejarán. Para abordar esta variabilidad, inicialmente planeamos admitir formatos comunes de boletos electrónicos, como PDF y XML, que ya se utilizan en muchas farmacias.

2024-10-10 07:33 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU3].
Hice algunos cambios en el hito M3 para desarrollar mejor el mecanismo de notificación y hacerlo más completo. En concreto, agregué la posibilidad de que el usuario configure notificaciones según sus preferencias, estableciendo umbrales mínimos de stock personalizables y alertas de fecha de vencimiento. Esto permitirá una mayor flexibilidad a la hora de adaptar las notificaciones a las necesidades específicas de cada usuario.

2024-10-10 22:05 UTC, hossam1522 reviewed
Como ha mencionado mi compañero, es un gran proyecto y cada vez te va quedando menos para superar el objetivo. He dejado un par de comentarios. ¡Ánimo con ello y no te desmotives!

2024-10-10 22:05 UTC, hossam1522 commented on docs/milestones.md
> +Analizar las historias de los usuarios e identificar los conceptos clave necesarios para abordar el problema en el desarrollo del MVP. Estructurar los conceptos principales basados en las necesidades
Como se me ha comentado y como viene explicado en el [guión](http://jj.github.io/IV/documentos/proyecto/1.Planificacion#explicaci%C3%B3n):

```
Los productos son siempre entregables. No son conceptos, hay que explicar qué es 
lo que se va entregar, cómo se sabe que es válido y el soporte concreto que va a tener. 
Lo esencial, en todo caso, es leer atentamente los milestones que se han entregado 
y verse uno mismo llevando a cabo el desarrollo del producto, sin ningún (o muy poco) 
material adicional.
```

En ningún momento se menciona nada de objetivos. Tienes que describir un producto, es decir, explicar qué se va a entregar, cómo saber su validez y cómo se va a entregar.

2024-10-10 22:05 UTC, hossam1522 commented on docs/milestones.md
> +
Si a este milestone le estás asignando las HUs 1 y 3, significa que las HUs no están secuenciadas correctamente. Dale una vuelta a eso.

2024-10-11 07:29 UTC, MatteoImbrosciano commented on docs/milestones.md
> +Analizar las historias de los usuarios e identificar los conceptos clave necesarios para abordar el problema en el desarrollo del MVP. Estructurar los conceptos principales basados en las necesidades
Modifiqué lo que me dijiste, definiendo los conceptos y la lógica de mi trabajo que faltaban. Espero estar bien y pedir una revisión lo antes posible para poder completar el objetivo. 
Gracias

2024-10-11 07:29 UTC, MatteoImbrosciano commented on docs/milestones.md
> +
lo arreglé

2024-10-11 09:43 UTC, jacarmona364 commented on docs/milestones.md
> +## [M1] Milestone 1: Creación y gestión  del inventario
Es una gran idea Matteo, de esta forma estás aún más cerca del apto en este objetivo. Se me ocurre que además se podría hacer una pequeña estimación acerca del tiempo que cubrirá la cantidad de cada medicamento restante, es decir, conociendo el tamaño de la medicina, cuánto se toma en cada dosis y cuántas dosis se toman al día, se puede saber para cuántos días nos queda medicamento. Es simplemente una idea sencilla por si quisieras ir un paso más allá y garantizar la satisfacción del cliente añadiendo valor al producto con algo que no se espera que haga la aplicación.

2024-10-11 09:44 UTC, jacarmona364 commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU2].
Excelente, tarea completada.

2024-10-11 09:48 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU2].
gracias, entonces esperaré la aceptación de Hossam y luego le pediré una revisión al profesor.

2024-10-11 09:56 UTC, jacarmona364 commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU3].
Ahora se ve mucho más completo, quizá se podría valorar si es pertinente separar este hito en dos, pues recuerda la premisa del PMV. Dale una vuelta de nuevo a M3 para ver si se podría trabajar sobre dos productos mínimos o si realmente el sistema de notificaciones no puede existir sin que el usuario pueda modificar la configuración de las mismas. Ya estás cerca del apto, amigo, ¡a terminar de pulirlo!

2024-10-11 10:08 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Historias de Usuario asociadas:** [HU3].
He modificado esta fase, el sistema enviará notificaciones configurables pero sin opciones de personalización avanzadas.

2024-10-11 11:37 UTC, hossam1522 commented on docs/milestones.md
> +**Objetivo**:
Me refería a que evitases usar la palabra `Objetivo`, ya que eso no es lo que se debe especificar en un milestone. Veo que has cambiado la descripción y considero que está correcta, ya que ahora sí has especificado lo que es el producto a entregar, así que simplemente quita la palabra. También considero que deberías aplicar esto al resto de milestones, porque creo que solo has modificado este y no los demás.

2024-10-11 11:37 UTC, hossam1522 commented on docs/milestones.md
> +- [HU3]: Usuario que quiere una visión clara y organizada de su inventario, incluidas las cantidades y las fechas de caducidad.
A lo que me refería aquí no era a explicar la HU, ya que la explicación está en el archivo específico de estas. Me refería a que no tiene sentido asociar la HU1 y la HU3 al milestone 1 y asociar la HU2 al milestone 2. No está ordenado. Deberías considerar cambiar el orden de las HUs de manera que la HU1 y HU2 estén asociadas al milestone 1 y la HU3 al milestone 2, manteniendo así el orden secuencial correctamente. Con cambiar el orden en el archivo `user_stories.md` y cambiar el número en este archivo, debería bastar y sobrar.

2024-10-11 11:38 UTC, hossam1522 commented
Te he dejado un par de comentarios intentando aclarar lo que expliqué la última vez. Échale un vistazo y me vuelves a solicitar revisión cuando sea necesario. ¡Ánimo!

2024-10-11 11:41 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Objetivo**:
Vale, lo cambiaré ahora mismo, no lo entendí.

2024-10-11 11:54 UTC, MatteoImbrosciano commented on docs/milestones.md
> +- [HU3]: Usuario que quiere una visión clara y organizada de su inventario, incluidas las cantidades y las fechas de caducidad.
Olvidé actualizar Minestone, por lo que todavía quedaban HU1 y HU3 porque antes tenía un HU4. Ahora creo que eso es correcto.

2024-10-11 11:58 UTC, MatteoImbrosciano commented
@JJ

2024-10-11 15:23 UTC, JJ requested changes
Davvero, se  hai messo "diagrammi UML" non hai capito bene il punto di questa classe, nonchè l'oggettivo 1 stesso.
Questo non è un essercizio. Dev'essere un vero documento di lavoro per cominciare a lavorare sin dal oggetivo prossimo (2)

2024-10-11 15:23 UTC, JJ commented on docs/milestones.md
> +- Código fuente que represente el modelo del dominio del problema, basado en las historias de usuario [HU1] y [HU2].
¿Qué es el modelo del dominio del problema?

2024-10-11 15:23 UTC, JJ commented on docs/milestones.md
> +- Diagramas UML que describan las relaciones entre las entidades clave y los procesos involucrados en la gestión de medicamentos y tickets electrónicos.
¿Quién ha pedido nunca diagramas de UML?

2024-10-11 15:24 UTC, JJ commented
@jacarmona364 @hossam1522 os agradecería que aprobaráis explícitamente, si fuera el caso.

2024-10-11 18:08 UTC, JJ requested changes
Comunque, fa un'ochiatta sulle [errori comuni](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md). Ci sono parecchi che magari hai caduto:

- Parla per la precisione di non metere diagrammi UML. Cerchi là, è il 4º punto.
- Criteri di funzionalitá (viabilidad) devono essere oggetivi.
- Non devi mettere detagli sul prodotto, perche trovare detagli si devi fare dal svilupattore tramite il processo di sviluppo agile.

Aspetto che mo sia un po' più chiaro

2024-10-11 18:08 UTC, JJ commented on docs/milestones.md
> +Entregar un modelo inicial del dominio que defina claramente las entidades clave y sus relaciones, basado en las historias de usuario. Este modelo incluirá conceptos como medicamentos, tickets electr
Se dici ché concetti vanno inclussi nel modello, stai facendo il modelo adesso e non serve nessun milestone.

2024-10-11 18:08 UTC, JJ commented on docs/milestones.md
> +## **[M0] Milestone 0: Modelado y planificación del dominio del problema**
per piacere, leggi cosa stai facendo qui. Si mettono parole che non fanno senso insieme. Cosa è "planificazione del dominio del problema"? Vai planificare cosa?

2024-10-11 18:08 UTC, JJ commented on docs/milestones.md
> +Se considerará factible cuando el código fuente entregado represente correctamente el dominio del problema en función de la información recopilada en las historias de usuario antes mencionadas.
Non si parla di fattibilità (cualunque sia ciò) ma di "vitalità" o "funzionalitá", cioè, che funciona: prodotto minimo funzionante. Quindi, devi dire quà "Come si sa che funziona?" "Factible" in spagnuolo e "che si può fare". Se è fatto, ecco, è fattibile

2024-10-11 18:08 UTC, JJ commented on docs/milestones.md
> +- [HU1]: Paciente que desea cargar tickets electrónicos para actualizar automáticamente el inventario de medicamentos.
Perchè metti tanti parole? Il codice della storia, e basta.

2024-10-11 18:08 UTC, JJ commented on docs/milestones.md
> +Entregar un sistema que permita mantener un registro completo del inventario de medicamentos, definiendo niveles mínimos y máximos para cada medicamento y monitoreando fechas de caducidad y uso. El s
Uno sistema è una parola troppo grossa. Guarda l'oggetivo 4, cosa chiedono là? Non cerchi "parolacce" per passare questo, non va così. Guarda de capire cosa vai fare quà sulla classe, e fare una descrizione precisa de come si sa che quello che hai fatto è a posto.

2024-10-11 19:44 UTC, MatteoImbrosciano commented on docs/milestones.md
> +- Diagramas UML que describan las relaciones entre las entidades clave y los procesos involucrados en la gestión de medicamentos y tickets electrónicos.
Eliminé todo lo que hacía referencia a los diagramas.

2024-10-11 19:44 UTC, MatteoImbrosciano commented on docs/milestones.md
> +## **[M0] Milestone 0: Modelado y planificación del dominio del problema**
Leí mejor lo que había escrito gracias a un colega que habla el idioma, y ​​el traductor escribió cosas que eran diferentes a mi razonamiento.

2024-10-12 06:29 UTC, JJ commented on docs/milestones.md
> +## **[M0] Milestone 0: Modelado y planificación del dominio del problema**
Se vuoi lo fai in inglese o pure italiano.

2024-10-12 15:34 UTC, MatteoImbrosciano commented
@JJ Ho letto nuovamente l'obiettivo-1, ho modificato i milestones, può darle un'occhiato a ciò che ho fatto. Così se ho sbagliato qualcosa la modifico. Grazie

2024-10-13 11:50 UTC, hossam1522 approved these changes
Teniendo en cuenta los cambios que has hecho después de las revisiones del profesor, considero que el objetivo 1 ya estaría listo para aprobarse.

2024-10-13 13:29 UTC, jacarmona364 approved these changes
Con las recomendaciones del profesor y en vista de los nuevos cambios introducidos en tu proyecto creo que has comprendido bien la finalidad de este objetivo, por mi parte también estaría aprobado.

2024-10-14 08:19 UTC, JJ requested changes
Sei più preso dell'oggetivo, ma ancora devi fare pocchi correzioni.

2024-10-14 08:19 UTC, JJ commented on docs/milestones.md
> +**Historias de usuario asociadas**:
Se l'hai scritto sopra, perchè metti questo quà anche?

2024-10-14 08:19 UTC, JJ commented on docs/milestones.md
> +El milestone será completado cuando el código represente correctamente el dominio del problema, permitiendo cargar tickets electrónicos y actualizar automáticamente el inventario.
Dominio da quale problema? Qui serve precisione, se hai detto sopra su quali HU vai lavorare, scrivi anche qui.

2024-10-14 08:19 UTC, JJ commented on docs/milestones.md
> +## **[M2] Milestone 2: Carga de tickets electrónicos**
Per piacere, leggi [il rapporto di soliti errori](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md) dove dice:

> En desarrollo ágil más allá de dos milestones por delante no tiene mucho sentido planificar. Pero si se hace, conviene que se mire la progresión de objetivos de la asignatura para que se ajusten, en lo posible, a lo que se encuentra ahí.

2024-10-14 08:19 UTC, JJ commented on docs/milestones.md
> +- [HU1]
Perchè si va il modello per HU1 e 2 se per questo milestone serve soltanto HU1? Si può dire que il milestone 0 è "minimo"?

2024-10-14 08:19 UTC, JJ commented on docs/milestones.md
> +**Historias de usuario asociadas**:
Non è detto che ci sono "storie di utente associate". Questo è una roba che qualcuno ha messo nel suo oggetivo, che è totalmente sbaliata e non serve a nulla. Sulle [errori soliti oggetivo 0](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md)

> Es un error demasiado frecuente mirar lo que ha hecho un compañero/a y ponerlo tal cual. Y en general, va a ser un error que va a perjudicar al profesor (que tendrá que revisar dos o tres o 10 veces lo mismo) pero también al estudiante, porque lo que se busca no es que el estudiante entienda formalmente lo que hay que poner, sino que empiece a usar unas metodologías determinadas que le ahorren trabajo (o simplemente le indiquen cómo hacer el trabajo) en un entorno de desarrollo determinado.

> Si se observa el mismo patrón de entrega en varios estudiantes, lo primero que indica es dejadez por parte del estudiante y falta de preocupación por aprender los objetivos de la asignatura. Dado que se puede entregar lo que se desee y el profesor lo corrige, a priori no hay ningún problema porque se le indica al estudiante el error (que en el caso del anterior estudiante puede simplemente haberse pasado por alto por ser el primero o porque hay elementos en la entrega que son correctos) pero a medio plazo no involucrarse con los objetivos de aprendizaje lleva a la frustración ("He puesto lo mismo que el compañero y me lo ha rechazado") trabajo adicional (hay que volver a enviar el objetivo hasta que esté claro que se saben aplicar las metodologías de cada uno de los objetivos) y eventualmente al abandono de la asignatura debido a esa frustración y al retraso que conlleva tener que corregir varias veces el objetivo entregado.

> En general, la mejor estrategia es tratar de entender de forma autónoma los conceptos y metodologías que se incluyen en cada objetivo. Si no se entienden bien, el profesor guiará hasta que se comprendan. Si simplemente se pone lo que ha puesto otro compañero, la corrección del profesor no va a comportar ningún aprendizaje, sino un bucle posiblemente infinito de entregas tomadas de otro compañero/a o de algún lugar; y no lo va a comportar simplemente porque no se ha hecho el esfuerzo que lleva a esa solución que se ha propuesto. Pero es que si se aprueba tampoco se va a aprender nada. "Me han aprobado lo que he copiado de no sé dónde". Bravo. No has aprendido nada, y lo que se aprende en un objetivo se tiene que aplicar en los siguientes. Si no has aprendido nada, tendrás que volver a hacer el esfuerzo de aprenderlo de todas maneras, y te costará mucho más trabajo cuanto más complejos sean los objetivos a alcanzar.

2024-10-14 12:55 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Historias de usuario asociadas**:
Ho eliminato la ripetizioni

2024-10-14 12:55 UTC, MatteoImbrosciano commented on docs/milestones.md
> +El milestone será completado cuando el código represente correctamente el dominio del problema, permitiendo cargar tickets electrónicos y actualizar automáticamente el inventario.
Ho cercato di rendere più chiara la descrizione

2024-10-14 12:55 UTC, MatteoImbrosciano commented on docs/milestones.md
> +## **[M2] Milestone 2: Carga de tickets electrónicos**
Ho letto il rapporto sugli errori comuni e ho capito l'importanza di non pianificare oltre le due tappe fondamentali nello sviluppo agile, ho rivisto il Milestone 2 seguendo le sue indicazioni ed ho eliminato dettagli superflui

2024-10-14 12:55 UTC, MatteoImbrosciano commented on docs/milestones.md
> +- [HU1]
Ho rivisto il Milestone 1, includendo [HU2] poiché anche il responsabile degli acquisti ha bisogno di gestire le scorte familiari con livelli minimi e massimi, così come il paziente. Per quanto riguarda il milestone 0, ho inteso che fosse "minimo" poiché introduce il modello di base

2024-10-14 12:55 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**Historias de usuario asociadas**:
Ho eliminato le storie utente e focalizzandomi sul sistema di notifiche delle scadenze dei medicinali e delle scorte minime.

2024-10-14 15:26 UTC, JJ commented on docs/milestones.md
> +## **[M2] Milestone 2: Carga de tickets electrónicos**
Devi risolvere ogni commento. Per la precisione, credevi che il titolo di questo milestone è corretto? Si parla di una funcionalità, non proprio di uno prodotto.

2024-10-14 15:37 UTC, JJ requested changes
Mi raccomando, devi capire cosa è una pietra miliare/prodotto di minima funcionalità e raccontare quà cosa vai chiedere dal svilupattore quando arrivi al oggetivo 2. 

Leggi [qui](http://jj.github.io/IV/documentos/proyecto/1.Planificacion#qué-son-los-hitos-o-milestones) cosa è un miliare. 

La checklist inclusa sulla guida ti può proprio aiutare:

> ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?

Ecco la principale, quella che devi essere risposta senza dubbio. Ma ancora di più:

> ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?

>  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?

> ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?

Amunì, e avanti.

2024-10-14 15:37 UTC, JJ commented on docs/milestones.md
> +Hay que entregar un modelo inicial el dominio del problema de la gestión automatizada de medicamentos, con los conceptos clave y sus relaciones, definiendo las entidades y agregados necesarios para e
Mi racommando, si devi parlare di quale SU (storia di utente?) serve a quello milestone quà. Cosa è "gestione automatizzata di medicamenti?" Se non si parla si SU, è imposibile per lo svilupattore di andare avanti. Mi racommando, leggi un'altra volta [la carta di soliti errori](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md#sobre-los-milestones):

> Aunque los milestones en principio no tienen por qué tener información sobre las historias de usuario, si hay varias historias de usuario hablar de "modelo del problema" o de "lógica de negocio" no es suficiente, porque las dos historias de usuario (o las 5) pueden tener diferentes aspectos del problema, o incluso ser problemas diferentes. En todo caso, siempre es conveniente ser preciso en el lenguaje, porque en el momento que se vaya a trabajar con un milestone determinado puede haber más historias de usuario, o menos, así que aclarar a qué parte del problema del cliente se circunscribe siempre es conveniente.

2024-10-14 15:37 UTC, JJ commented on docs/milestones.md
> +**Historias de usuario asociadas**:
Ma e quà dove non devono stare. Un'altra volta, soliti errori:

> Para empezar, el [error frecuente del objetivo 0 mencionado en la introducción](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md) se sigue produciendo. En este caso, cosas como: - Poner el "objetivo" de un milestone. - **Poner "HUs asociadas"** - Poner primero "modelo del problema", luego "estructura del problema", y luego "dominio del problema", sin entender en ningún caso de qué se está hablando. - Poner 4 o 5 milestones. - Poner "el milestone lo validará el validador".

Se non si capisce bene cosa stai a fà e perchè, è improbabile andare avanti. Devi proprio capire cosa é un milestone, perchè si descrive così, e a cosa serve.

2024-10-15 14:15 UTC, MatteoImbrosciano commented on docs/milestones.md
> +## **[M2] Milestone 2: Carga de tickets electrónicos**
Ho riformulato il Milestone 2 per concentrarmi maggiormente sul prodotto, come suggerito. Invece di descrivere semplicemente una funzionalità, ora il milestone è focalizzato sulla creazione di un sistema completo di gestione dei ticket elettronici

2024-10-15 14:16 UTC, MatteoImbrosciano commented on docs/milestones.md
> +Hay que entregar un modelo inicial el dominio del problema de la gestión automatizada de medicamentos, con los conceptos clave y sus relaciones, definiendo las entidades y agregados necesarios para e
Ho riletto la definizione di pietra miliare e la checklist per comprendere meglio cosa ci si aspetta da ogni milestone. Mi sono reso conto che devo essere più specifico nel descrivere cosa il team di sviluppo dovrà effettivamente consegnare e non io. Ho rimosso termini generici come "gestione automatizzata di medicinali" e ho chiarito meglio quali entità e relazioni dovranno essere implementate nel milestone.

2024-10-15 14:20 UTC, MatteoImbrosciano commented
@JJ Ho cercato di eseguire al meglio tutte le tue indicazioni. Spero vada tutto bene

2024-10-15 15:15 UTC, JJ commented on docs/milestones.md
> +## **[M2] Milestone 2: Carga de tickets electrónicos**
Ti pare che un sistema *completo* si possa chiamare "minimo"?

2024-10-15 15:16 UTC, JJ commented on docs/milestones.md
> +- [HU1]
Il milestone 1 non è mai piú funcionalità, perche non c'è nulla funcionalità dopo il milestone 0.

2024-10-15 15:22 UTC, JJ requested changes
Ci sono infinite combinazione de parole che non centrano niente con l'oggetivo qui. L'algoritmo de cambiare una parola o magari 40 per cercare di riuscire non finisce mai.
Se non sai cosa è una pietra miliare, è meglio se si chiede al professore, si cerca sulla Internet, o si chiede sul gruppo Telegram.

2024-10-15 15:22 UTC, JJ commented on docs/milestones.md
> +Hay que entregar un sistema que modele el problema de la gestión de medicamentos, con los conceptos clave y sus relaciones, definiendo las entidades y agregados necesarios para el desarrollo del PMV,
Soltanto hai canviato "modelo inicial del dominio del problema" per "sistema que modele". Cosa è un sistema? Ché stai a dire quà?

2024-10-15 15:22 UTC, JJ commented on docs/milestones.md
> +## **[M1] Milestone 1: Sistema de gestión de tickets electrónicos**
Nè "sistema de gestión" nè "gestión" descrivono uno prodotto.

2024-10-17 05:17 UTC, JJ requested changes
Non capisco niente de cosa stai facendo e perchè.

2024-10-17 05:17 UTC, JJ commented on docs/user_journeys.md
> +## 2. Marco
Non capisco. Perchè fai ciò?

2024-10-17 05:17 UTC, JJ commented on docs/user_journeys.md
> +Cada vez que compra medicamentos, recibe un ticket electrónico que contiene detalles como el nombre del medicamento, la cantidad y el precio. Actualmente, debe transcribir manualmente esta informació
Non capisco bene. C'è uno comento qualunque che vuoi rispondere qui?

2024-10-17 05:17 UTC, JJ commented on docs/user_stories.md
> +## [HU1] Paciente que desea ingresar manualmente sus medicamentos
Ho fatto uno commento qui e per ciò si fa il aggiornammento?
Da prima non c'era nessun problema, adesso non è veramente una US. Ti pare che mo sia meglio ?

2024-10-17 07:51 UTC, JJ requested changes
Dai una occhiata all'errori comuni, mi racommando

2024-10-17 10:03 UTC, JJ requested changes
Penso che hai presso una buona strada, ma manca anca un po. Amunì!

2024-10-17 10:03 UTC, JJ commented on docs/milestones.md
> +È necessario fornire un sistema iniziale che rappresenti la base del problema, basato sulle storie degli utenti [HU1] e [HU2]. Questo modello includerà le entità chiave e le loro relazioni necessarie
Se lo fai così, markdown cerca se hay definito [H1] giù al documento. Mi sa che non conosci bene [markdown](https://learn.microsoft.com/it-it/contribute/content/how-to-write-links), forse dovresti dare un'occhiata. Pure sopra ci sono collegamenti di aiuto. [Qui](https://experienceleague.adobe.com/it/docs/experience-manager-cloud-service/content/sites/administering/content-fragments/markdown) c'è un altro, spiegato più bene, dove si fa ciò che magari vorresti fari quà, un "collegamento di riferimento".

2024-10-17 10:03 UTC, JJ commented on docs/milestones.md
> +Il traguardo sarà completato quando il codice rappresenterà correttamente la base problematica.
Di quali SU? Già stanno sopra, ma la precisione è fondamentale. Se si rimette qui, è un problema?

2024-10-17 10:03 UTC, JJ commented on docs/milestones.md
> +È necessario sviluppare un sistema che permetta all'utente di visualizzare e gestire l'inventario dei medicinali. Il sistema dovrà fornire una panoramica chiara e in tempo reale dei medicinali dispon
Ti pare che soltanto in due miliari l'utente può "visualizzare"?
Questo miliare quà e collegato all'oggetivo 4, e si debe completare il lordo di ciò là, con altri parti sull'oggetivo 5 e 6. Fai una occhiata la. Si parla de la "logica di primo livello" (*business logic*), e basta. 
Anchi, devi *sempre* dire con quali US stiamo lavorando.

2024-10-17 10:03 UTC, JJ commented on docs/milestones.md
> +**[M2] Milestone 2: Integrazione dei tickets electrónicos**
Non so cosa è "integrazione", ma so che oltre le due primi miliari non si va, e se si anda là si fa una cosa diversa. Tira un'occhiata all'oggetivi oltre il 6 per checkare di cosa sto parlando.

2024-10-17 10:03 UTC, JJ commented on docs/milestones.md
> +È necessario prevedere una funzionalità che permetta di caricare i biglietti elettronici in formato PDF o XML e di aggiornare automaticamente l'inventario con le informazioni estratte dai ticket. Ciò
Invece devi pensare di fare un deployment a la nuvola, che e ciò di cui parliamo qui.

2024-10-18 09:39 UTC, MatteoImbrosciano commented on docs/milestones.md
> +**[M2] Milestone 2: Integrazione dei tickets electrónicos**
Il termine "Integrazione" è un sinonimo "incorporare", quindi vado ad incorporare le funzionalità che successivamente vado a richiedere nel milestone

2024-10-18 10:40 UTC, JJ commented on docs/milestones.md
> +**[M2] Milestone 2: Integrazione dei tickets electrónicos**
Voleva dire que non è un prodotto. Il punto qui è que non servono miliari oltre il M1

2024-10-18 10:50 UTC, JJ approved these changes
Manca uno commento, ma penso que è meglio se lo fai dopo. Mi racommando, prima di andare al prossimo oggettivo.
Ricorda que devi spostare i miliari e US al spagnolo su GitHub, US come "issues" e miliari come "milestones"

2024-10-18 10:50 UTC, JJ commented on docs/milestones.md
> +Il traguardo sarà completato quando il codice rappresenterà correttamente la base problematica.
Mi racommando, guarda su anche.

2024-10-18 11:24 UTC, merged

2024-12-17 16:25 UTC, JJ reviewed
Mi pare che ho andato troppo snello in passare questo oggetivo, perche non è proprio come doveva. Il problema ha devenito più grande, perchè non mi pare che tu abbia capito cosa è una storia di utente, e quindi è impossibile di svilupare tests per provare che l'utente è soddisfato. Neanche hai aggiunto informazione sulle recette da dove viene stratta la informazione sulle medicamenti.

Quindi, cosa devi fare
1. Capire bene cosa è uno SU e una pietra miliare.
2. Scrivere bene almeno 1 US come t'ho detto sotto
3. Andare avanti al oggetivo 4.

Spiace avere fatto passare questo senza una supervisione adequate. Mi racommando, fai i cambiamenti che ti dico qui. Quando sei pronto con la nuova US dimmi pure.

2024-12-17 16:25 UTC, JJ commented on docs/milestones.md
> +- **HUs asociadas**: [HU1], [HU2]
Questo è soltanto valido perchè sei stato rapido per farlo. Tutti i seguenti non hanno pottulo scrivere "HUs asociadas", perchè nessuno capiva cosa erano "SU collegate". Ora capisco che neanche tu l'hai capito.
Un milestone deve stare collegato a una storia utente, perche se non è impossibile conoscere lo scopo dello milestone. E se hai soltanto due HU e metti tutti i due, non stai facendo nulla sulla divisione del problema. Devi chiarire quale HU vai lavorare. Doveva avere messo più attenzione, io ed anche tù. Questa è la ragione perchè devi fare revisioni ai compagni: per capire bene cosa si deve fare, nonchè incrementare el voto perchè il 20% e dipendente di ciò

2024-12-17 16:25 UTC, JJ commented on docs/milestones.md
> +Es necesario desarrollar un sistema que permita al usuario visualizar y gestionar el inventario de medicamentos. El sistema deberá proporcionar una vista clara y en tiempo real de los medicamentos di
Ti pare un bel lavoro fare una "struttura del problema" o cualunche cosa che hai detto sopra su *due US* e poi lavorare e poi dire soltanto 1? Perchè si fa "la struttura del problema" di "US collegate" 1 e 2 e dopo soltanto la 1?Sai veramente cosa stai dicendo qui?

2024-12-17 16:25 UTC, JJ commented on docs/milestones.md
> +En este hito, el usuario podrá insertar, modificar y eliminar medicamentos del sistema, además de poder visualizar las cantidades y los detalles como la fecha de caducidad.
Veramente non capisco come ciò ha pottuto andare via. Una pietra miliare non include  mai  compiti. È soltanto la descrizione de un prodotto minimo. Se si parla di fare questo o quello, a che serve la US? Si sa già cosa fare, perchè parlare di pietre miliari e cosí via? Leggi pure [i errori comuni](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md):


> El exceso de detalles hace que se fuerce a soluciones determinadas, y hace que haya que cambiar una cantidad excesiva de cosas. Los milestones son agrupaciones de productos de complejidad creciente, que creen diferentes niveles de abstracción a la hora de trabajar con el problema. Decir que uno tenga "2 cosas" y otro "3 cosas" divide de forma artificial el problema, porque igual de trabajo cuesta programar para 3 cosas que para 5.

>    Otro ejemplo es decir "hacer un modelo que incluya la clase a, b y la c". "Hacer un modelo" es precisamente saber cuales son esas clases y qué es lo que incluyen o cómo se comportan.

2024-12-17 16:25 UTC, JJ commented on docs/milestones.md
> +- **HUs asociadas**: [HU1]
Non stai dicendo ne il prodotto, ne chè lo fa viabile. Non capisco como è possibile che hay fatto correttamente il oggetivo due, e non capisco neanche perchè @wickeet non ha segnato che c'erano problemi con questi pietre miliari.

2024-12-17 16:25 UTC, JJ commented on docs/user_stories.md
> +necesito un sistema que me permita insertar manualmente los medicamentos en el inventario,
Questo é un compito, non è un problema. Il "user journey" sopra è proprio una US, perche, tranne l'ultima frase, è semplicemente un problema.

2024-12-17 16:25 UTC, JJ commented on docs/user_journeys.md
> +Cuando compro medicamentos, a menudo pierdo el control de lo que ya he comprado y termino comprando medicamentos innecesarios. Esto se traduce en un desperdicio de dinero y en el riesgo de tener medi
Se si toglie l'ultima frase, ti pare che questo è un problema?
Pure devi aggiungere detagli su dove stanno i biglieti e che informazione contengono. Mi sembra che c'era qua, dove ha finito?

2024-12-17 19:16 UTC, MatteoImbrosciano commented
Ho aggiornato il milestones 1, la HU2 e la user_journeys. @JJ